# Read the Docs build config. Commit this file to your repo and Read the Docs
# will build the site automatically on every push.
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
